### ISSUE TITLE
Can't scroll test results in pop-up

### ISSUE THREAD

**Issue by nicpayne713** [rcarriga/vim-ultest#101]
**Describe the bug**
Info: Neovim 0.6, python 3.8, pytest

This may not be a true bug and instead if vim-noobish-ness on my part (only been in nvim for about 8 months) but when I run tests I can see the pytest output if I put my cursor on a test but I cannot scroll the output like I see in the sample gifs.

**To Reproduce**
Not sure how to reproduce if this isn't an issue for you already

**Expected behavior**
I think I'd expect to be focused in on the pop up (is it a vim terminal buffer?) and then when I'm done I'd :q or something to get back to my code.

**Comment by rcarriga** [comment]
You can jump to the output window with the `<Plug>(ultest-output-jump)` mapping and once in the window you are correct it is a terminal buffer which you move around in like any other

**Comment by nicpayne713** [comment]
Awesome thank you! I didn't know what that notation meant - some googling got me there! Thanks again for the quick reply!

**Comment by wookayin** [comment]
Or `:call ultest#output#jumpto()`
