### ISSUE TITLE
Awesome nvim / vim config, share please?

### ISSUE THREAD

**Issue by TrevorIkky** [rcarriga/vim-ultest#118]
Hello, I couldn't help but notice the colourful nvim setup you have in the screenshots you added in the readme file. Would you mind sharing your set up. Thanks in advance !

**Comment by rcarriga** [comment]
I have my dotfiles in a repo already with all of my config for neovim :smile: The colour scheme is my own custom one here https://github.com/rcarriga/dotfiles/blob/master/.config/nvim/lua/colors.lua

**Comment by TrevorIkky** [comment]
Thanks man! I really appreciate it!
