### ISSUE TITLE
Errors after install plugin.

### ISSUE THREAD

**Issue by voitd** [rcarriga/vim-ultest#12]
Thanks for this great plugin! But after installation I get this error:

<img width="865" alt="error" src="https://user-images.githubusercontent.com/60138143/101959203-8b0c1b80-3c0d-11eb-8a64-175b44591665.png">

Do you need any logs for debugging?

**Comment by rcarriga** [comment]
It looks like you need to run `:UpdateRemotePlugins`. I will add this to the documentation

**Comment by voitd** [comment]
Thanks! It was installed fine after installation in this way:
```bash
Plug 'rcarriga/vim-ultest', { 'do': ':UpdateRemotePlugins' }
```
