### ISSUE TITLE
Error on new installation

### ISSUE THREAD

**Issue by cpfaff** [rcarriga/vim-ultest#15]
**Describe the bug**
After install latest version starting vim gets me the following error message. The error comes back every few seconds. A normal usage of vim is impossible with that.

```
Error detected while processing function ultest#handler#get_nearest_test:
line    2:                                                                                                                                                                                                
E117: Unknown function: _ultest_get_nearest_test
Error detected while processing function ultest#handler#get_nearest_test:
line    2:
E15: Invalid expression: _ultest_get_nearest_test(a:line, a:file_name, a:strict)
```

**To Reproduce**

Install latest version of your plugin. Start vim. Wait.

**Expected behavior**
Produce no error message on vim start.

**Screenshots**

**Additional context**

**Comment by rcarriga** [comment]
You need to run `:UpdateRemotePlugins` for NeoVim. This often seems to missed in the install instructions, I will add better handling for this

**Comment by cpfaff** [comment]
I see. Thanks. Plug has support for calling post installation hooks. That means this installs it properly:

```
Plug 'rcarriga/vim-ultest', { 'do': ':UpdateRemotePlugins' }

```

**Comment by rcarriga** [comment]
Perfect I'll add that to the docs thank you!
