### ISSUE TITLE
Getting error when installing the plugin

### ISSUE THREAD

**Issue by farzadmf** [rcarriga/vim-ultest#17]
**Describe the bug**
I add the following line to my `~/.vimrc`:
```
Plug 'rcarriga/vim-ultest', { 'do': ':UpdateRemotePlugins' }
```

And I'm getting the following error:
```
Error detected while processing /home/farzad/.vim/plugged/vim-ultest/plugin/ultest.vim:
line  175:
E995: Cannot modify existing variable
```

**To Reproduce**
Add the line to `~/.vimrc` and do `:PlugInstall`

**Expected behavior**
I shouldn't see any error (I think!)

**Screenshots**

**Additional context**
I'm using `neovim` and `vim-plug`, my `neovim` version:
```
NVIM v0.4.4
Build type: Release
```

**Comment by rcarriga** [comment]
Hmm it looks like this is a bug with 0.4.4. Can you pull the latest version of the plugin and try again?

**Comment by farzadmf** [comment]
Great, seems to be fine with the latest master. I think it would be helpful if the commit was linked to the issue :slightly_smiling_face:
