### ISSUE TITLE
Getting error when opening a test file

### ISSUE THREAD

**Issue by farzadmf** [rcarriga/vim-ultest#18]
**Describe the bug**
I'm opening a test file (a `go` file in my case), and I'm getting the following error:
```
python3-rplugin-host: Async request caused an error:
Vim(let):E117: Unknown function: list2str
```

**To Reproduce**
Open a `..._test.go` file

**Expected behavior**
I shouldn't see any errors

**Screenshots**

**Additional context**
I have `pynvim` package installed, and I'm not sure what's missing

The message doesn't seem to be directly coming from the plugin, but since this plugin lists `pynvim` as requirements, and when I disable this plugin, I can open the test file, I'm guessing the error is coming from this plugin

**Comment by cpfaff** [comment]
Same here with a python file.

**Comment by rcarriga** [comment]
Should be good now! It will fall back to a slightly slower implementation but should be completely negligible.
