### ISSUE TITLE
Make it clear that popup delay depends on `updatetime` option

### ISSUE THREAD

**Issue by metalelf0** [rcarriga/vim-ultest#22]
**Describe the bug**

I'm not entirely sure this is related to `vim-ultest` rather than nvim itself, but when I first installed the plugin, the popup window with the failed test information took exactly 4 seconds to display (the one that pops up on hover on the first line of the failed test).

I checked with `:options` and found out that I had `updatetime` set to `4000` (which, I guess, is the default value). Reducing it to `100` actually makes the popup window appear instantly.

However, this will cause a lot more writes (40 times more) to the swap file, if it's used, therefor raising a potential issue on SSD devices. I would add this information to the readme, either telling users to disable swap files or to know the tradeoffs of a low `updatetime`.

Thanks for this plugin and keep up the great work!

**Comment by rcarriga** [comment]
Or a minimal `init.vim` would be the easiest way for me to reproduce as well to be sure I can run your exact setup and exclude other plugins
