### ISSUE TITLE
Ultest does not detect custom vim-test runners

### ISSUE THREAD

**Issue by weilbith** [rcarriga/vim-ultest#28]
**Describe the bug**
While `vim-test` comes with a sane list of runners per default, it is far from complete. But that is not of an issue as it is pretty simple to just add new runners to the plugin. I have such runners in my setup. [Here](https://github.com/weilbith/vim-blueplanet/blob/master/pack/plugins/start/test_/autoload/test/typescript/jest.vim) for example I add `jest` for the filetype `typescript`. This runner is very simple as it basically just brings the already existing `jest` runner for `javascript` into the `typescript` filetype plus tiny additions. This was/is working perfectly fine with `vim-test`.
So if I open a related test file for this and run for example `:TestFile` this works. If I now run `:Ultest` nothing happens. If I open the summary window with `:UltestSummary` the list of detected tests is empty.!

Logs should be created using `ULTEST_LOG_LEVEL=DEBUG ULTEST_LOG_FILE=vim-ultest.log nvim <test-file>` and added here as well

```
10:44:13 | INFO | MainThread | logging.py:create_logger:71 | Logger created
10:44:13 | DEBUG | MainThread | __init__.py:__init__:40 | Handler created
10:44:13 | DEBUG | Thread-1 | jobs.py:_handle_coroutine:42 | Starting job with group run_all
10:44:13 | INFO | Thread-1 | __init__.py:run:101 | Running all tests in tests/unit/router/guards/global.spec.ts
10:44:13 | DEBUG | Thread-1 | jobs.py:_handle_coroutine:57 | Finished job with group run_all
10:44:21 | DEBUG | MainThread | __init__.py:update_positions:160 | No patterns found for tests/unit/router/guards/global.spec.ts
```

**To Reproduce**
Create a custom runner and put into your path somewhere under `autoload/test/<filetype>/<runner>.vim`.  As an example you can take the example I liked above.  Add the runner to your custom runners with `let g:test#custom_runners = { '<filetype>': ['<runner>'] }`. Depending on your exact setup you might need to enable the runner in `test#enabled_runners`. Now open a test file for this `<filetype>` which uses this `<runner>`. Try to run a `vim-test` command  to run a test case and see it succeed. Now try the same with `vim-ultest`. It does not work.

**Expected behavior**
`vim-ultest` can pickup all custom runners for `vim-test`.

**Comment by rcarriga** [comment]
The problem is in the logs
```
10:44:21 | DEBUG | MainThread | __init__.py:update_positions:160 | No patterns found for tests/unit/router/guards/global.spec.ts
```
You need to define `g:test#typescript#jest#patterns` for your custom runner, vim-ultest otherwise has no way of knowing how to find tests

**Comment by weilbith** [comment]
According to the docs of `vim-test` this variable is called `g:test#typescript#jest#file_pattern`. And this variable is set for me and contains `'.spec\.ts$'`. And only because this variable is set `vim-test` runs successfully for this specific scenario.

**Comment by rcarriga** [comment]
The file pattern is a different variable. You haven't run into the problem with missing test patterns because your runner uses the existing jest runner function `build_position` which internally uses `g:test#javascript#patterns` ([here](https://github.com/vim-test/vim-test/blob/f5619460b77b9b444311aa3b6f31ecd9ffdaa6d8/autoload/test/javascript/jest.vim#L48)). 

There is no way I can see that vim-ultest could infer these patterns should come from a totally unrelated language (as far as it can know, obviously typescript is related to javascript).

Easy solution that you can use is to just this line add to your runner
```vim
let g:test#typescript#patterns = g:test#javascript#patterns
```

**Comment by weilbith** [comment]
Ah, sorry. I wasn't aware about this. 🙊 
Your suggested solution sounds reasonable for me. I just put it into my custom runners and it works like charm. Thank you very much for the help! 🙃
