### ISSUE TITLE
Opening a new file causes E484: Can't open file

### ISSUE THREAD

**Issue by ovikk13** [rcarriga/vim-ultest#30]
### Describe the bug
Opening a new file causes the following error: (this does not apply to already existing files)
```
:e test.js     Error detected while processing function <SNR>52_MonitorFile[4]..test#test_file[1]..test#determine_runner[9]..test#base#t
est_file[1]..test#javascript#denotest#test_file:
line    5:
E484: Can't open file test.js
Press ENTER or type command to continue
```
If you press enter then the file is opened as expected.

This only applies to some file types, for example: `js`, `vim`, `php`. File like `lua`, `test` work just fine. I'm assuming it only applies to files with a registered test runner.

Logs:
```
10:22:06 | INFO | MainThread | logging.py:create_logger:71 | Logger created
10:22:06 | DEBUG | MainThread | __init__.py:__init__:40 | Handler created
10:22:11 | INFO | MainThread | logging.py:create_logger:71 | Logger created
10:22:11 | DEBUG | MainThread | __init__.py:__init__:40 | Handler created
```

### To Reproduce
```
nvim -u NORC
:e test.js # open a new file
```

### Expected behavior
No error should occur. Should simply open the new file.

### Additional context
**Neovim version**: `NVIM v0.5.0-dev+1186-g8665a96b9` (built from master with Release)\
vim-ultest and vim-test updated to latest 

**Python3 checkhealth:**
```
## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.8.5
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.
```
Using latest version of vim-test and vim-ultest as of this writing.

Removing ultest fixes this issue.

Thank you for this awesome plugin! Hope you can fix this minor issue:)

**Comment by rcarriga** [comment]
Thanks for the report! Should be working fine now, please let me know if not
