### ISSUE TITLE
Colorscheme

### ISSUE THREAD

**Issue by arpangreat** [rcarriga/vim-ultest#38]
What is the colorscheme you are using on the nvim screenshot ?? 
It would be helpful :smiling_face_with_three_hearts:

**Comment by rcarriga** [comment]
Sure it is just from my dotfiles. I recently switched to lua as it looks a lot cleaner without all the line breaks 😅 
Code is here https://github.com/rcarriga/dotfiles/blob/master/.config/nvim/lua/colors.lua
And it is loaded from here https://github.com/rcarriga/dotfiles/blob/master/.config/nvim/colors/haslo.vim
