### ISSUE TITLE
Go: Configuration for using delve DAP rather than vscode-go

### ISSUE THREAD

**Issue by RonanMacF** [rcarriga/vim-ultest#48]
Not sure if this is a bug or a user error but I'm leaning towards the latter :) In the docs there is a sample configuration for vscode-go which parses the output to see if a test failed or not because there is no error code returned. With delve an error code is returned so this is not an issue. 

Using the following configuration
```
	dap = {
		type = "go",
		name = "Debug test",
		request = "launch",
		mode = "test", -- Mode is important
                program = "${workspaceFolder}",
                  -- program = "${file}"
                dlvToolPath = vim.fn.exepath("dlv"),
                args = args
	},
```
`:DebugNearest` and `:debug` does successfully stop at breakpoints. The issue is that the sign stays at 'running' as it appears the error code is not checked. I'm not sure if I am missing a particular configuration above, I thought code checking would have been the default.

Anyways this is super low priority, running `:Ultest` afterwards will refresh the signs.

**Comment by rcarriga** [comment]
So Delve is actually not reporting back the exit code of the target program (in this case the test).  The exit code is sent through an exit event https://microsoft.github.io/debug-adapter-protocol/specification#Events_Exited. Now vscode-go thankfully outputs the stdout/stderr of the program so we can parse the result. From what I can tell, delve doesn't do this. You can check the nvim-dap debug logs for output events. For example
```lua
[ DEBUG ] 2021-06-12T08:44:14Z+0100 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:492 ]	{
  body = {
    category = "stdout",
    output = "--- FAIL: TestD (1.89s)\n    main_test.go:11: 2 != 2\nFAIL\n"
  },
  event = "output",
  seq = 27,
  type = "event"
}
```

If you can figure out a way for delve to send the exit code or output of the target then you can get a result but without that there is absolutely no way that vim-ultest can know what the result is.

**Comment by RonanMacF** [comment]
Would reading these exit events be a reasonable feature request? It seems
like this events were made for the purpose of communicating error codes

**Comment by rcarriga** [comment]
Sorry I wasn't clear, absolutely the exit events are already read to get the exit code from adapters that send it (e.g. debugpy). The problem is that neither of the go debug adapters (vscode-go and delve) emit these events. vscode-go **does** send the output of the target process however which is what we can use the infer it. Delve doesn't send output either so there is no info to infer from.
