### ISSUE TITLE
Unicode icons are not portable

### ISSUE THREAD

**Issue by HiPhish** [rcarriga/vim-ultest#51]
Several of the default icons used are in the private use area of Unicode, which means they can vary wildly from font to font and will most likely look like gibberish to anyone who is not using the exact same font as you. I propose replacing the defaults with something standardized; it will not look the same to everyone, but at least it will look like more or less similar.

The signs in question are:

- `g:ultest_pass_sign`
- `g:ultest_fail_sign`
- `g:ultest_running_sign`
- `g:ultest_not_run_sign`

I propose:

- `g:ultest_pass_sign`: `✓` Check Mark U+2713 
- `g:ultest_fail_sign`: `🗲` Lightning Mood U+1F5F2
- `g:ultest_running_sign`: `🗘` Clockwise Right and Left Semicircle Arrows U+1F5D8
- `g:ultest_not_run_sign`: `?` Question Mark U+003F

**Comment by rcarriga** [comment]
Oh TIL, thank you for flagging. I've gone with the multiplication sign instead of lightning as it feels more consistent. Also chose the heavy versions of the check and multiplication.
