### ISSUE TITLE
[Feature Request] Provide :UltestAttachDebug command

### ISSUE THREAD

**Issue by RonanMacF** [rcarriga/vim-ultest#52]
New issue to replace  #49 to keep things a bit cleaner

The functionality to attach to current processes and open a debugger in a floating window works well using `:UltestAttach`. What would be interesting is if similar functionality could be added to attach to programs running using DAP. 

For example, with debugpy we could add 
```
import debugpy
debugpy.listen(5678)

debugpy.beakpoint() 
```

Then running `:UltestAttachDebug` would attach to this instance and open the tray/sidebar.

Would something like this be feasible?

**Comment by rcarriga** [comment]
Closing as no response, feel free to reopen
