### ISSUE TITLE
Jest test freeze, but works with vim-test

### ISSUE THREAD

**Issue by smichaud** [rcarriga/vim-ultest#54]
Typescript, jest
Running a test freeze

Running it directly with [vim-test](https://github.com/vim-test/vim-test) works properly.

![image](https://user-images.githubusercontent.com/2299396/123185509-14759380-d464-11eb-9add-ec41374e5bc6.png)

Log:
```
...
20:45:01 | DEBUG | Thread-1 | __init__.py:_handle_coroutine:78 | Finished job with group update_positions
20:45:07 | INFO | MainThread | __init__.py:run_nearest:125 | Running nearest test in src/pipes/tests/PipeForm.test.tsx at line 55
20:45:07 | DEBUG | MainThread | __init__.py:_register_started:281 | Registering should_render_form,_header_and_submit_button-4681889750434716771 as started
20:45:07 | DEBUG | Thread-1 | __init__.py:_handle_coroutine:58 | Starting job with group should_render_form,_header_and_submit_button-4681889750434716771
20:45:07 | DEBUG | Thread-1 | processes.py:run:50 | Starting test process should_render_form,_header_and_submit_button-4681889750434716771 with command ['node_modules/.bin/react-scripts', 'test', '-t', '^<PipeForm> should render form, header and submit button$', 'src/pipes/tests/PipeForm.test.tsx'], cwd = None, env = None
20:45:08 | DEBUG | Thread-3 | handle.py:forward:85 | Writing data to output file
20:45:08 | DEBUG | Thread-3 | handle.py:forward:85 | Writing data to output file
20:45:08 | DEBUG | Thread-3 | handle.py:forward:85 | Writing data to output file
20:45:08 | DEBUG | Thread-3 | handle.py:forward:85 | Writing data to output file
20:45:08 | DEBUG | Thread-3 | handle.py:forward:85 | Writing data to output file
20:45:08 | DEBUG | Thread-3 | handle.py:forward:85 | Writing data to output file
...
```
Log indicates running: ['node_modules/.bin/react-scripts', 'test', '-t', '^<PipeForm> should render form, header and submit button$', 'src/pipes/tests/PipeForm.test.tsx'], cwd = None, env = None

Running this command manually works properly: `node_modules/.bin/react-scripts test -t '^<PipeForm> should render form, header and submit button$' src/pipes/tests/PipeForm.test.tsx`

**Comment by rcarriga** [comment]
I'm going to need some more details unfortunately. Does this happen with any Jest test? I can see the program is outputting something, can you run `:UltestAttach` on the test line to see the current output? It'd be great also to see the full logs. If you've got sensitive information in them like file names, feel free to substitute with `foo/bar.tsx` etc.

**Comment by smichaud** [comment]
Wow, I am kind of dumb. React script run using watch by default, so the process never stop. 
Based on [this issue](https://github.com/facebook/create-react-app/issues/784#issuecomment-392497169) you can add a `--watchAll=false` flag to disable it. 

Using [vim-test](https://github.com/vim-test/vim-test) I can pass arguments when I run tests (`:TestNearest --watchAll=false`). 
This does not seem to work with Ultest. Is there some way to add arguments to the runner? I think I might like for Pytest too from time to time.

**Comment by smichaud** [comment]
Nice! For anybody else having the same problem, the runner is actually `reactscripts`, so I added this to my init.vim

```
let test#javascript#reactscripts#options = "--watchAll=false"
let test#javascriptreact#reactscripts#options = "--watchAll=false"
let test#typescript#reactscripts#options = "--watchAll=false"
let test#typescriptreact#reactscripts#options = "--watchAll=false"
```
No sure they are all required but 🤷‍♂️...


The ability to add arguments to commands is honestly "candy/nice-to-have".

**Comment by rebuilt** [comment]
@smichaud Thank you.  I was having the same issue.  This helped me solve it.
