### ISSUE TITLE
Error "no notification handler registered" on diff

### ISSUE THREAD

**Issue by jens1205** [rcarriga/vim-ultest#63]
**Describe the bug**
Using vim-fugitive, the command ":Git difftool -y master" spams me several (4) times with the error message.

Comment https://github.com/rcarriga/vim-ultest/issues/44#issuecomment-859566430 looks similar

`no notification handler registered for "/Users/myuser/.local/share/nvim/site/pack/packer/start/vim-ultest/rplugin/python3/ultest:function:_ultest_update_positions"`

Enabling debug logs shows nothing, no matter if the command is started manually or via commandline (`ULTEST_LOG_LEVEL=DEBUG ULTEST_LOG_FILE=vim-ultest.log nvim -c ":Git difftool -y master"`)

**To Reproduce**
:Git difftool -y 

**Expected behavior**
No error

**Screenshots**
n/a

**Additional context**
n/a

**Comment by rcarriga** [comment]
Thanks for the report! Please try with the latest commit :grin:
