### ISSUE TITLE
Undetected Tests

### ISSUE THREAD

**Issue by Chaitanyabsprip** [rcarriga/vim-ultest#64]
Language: dart/flutter
The tests aren't detected if the description of the text is on the next line (due to it being too long).

If I cut out a few words out of the description such that the description is on the sae line as the function call of test(), the tests are detected.

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/55058351/130137300-3dc3dabd-e71d-4f8e-bdbd-81aba8cf5fc0.png">

**Comment by rcarriga** [comment]
Can you run tests using `vim-test` (i.e. `:TestNearest`)?

**Comment by Chaitanyabsprip** [comment]
The nearest test it detects are the one sapart from these two tests.

**Comment by rcarriga** [comment]
Yep so this is a problem with how vim-test finds tests so you'll have to raise an issue there. If a solution can be found I can port it to vim-ultest as well :smile:

**Comment by sidlatau** [comment]
This problem is fixed in vim-test: https://github.com/vim-test/vim-test/commit/9895268249f88ef67d10a20cc1a020a40096a1d9

**Comment by rcarriga** [comment]
LGTM, thanks for fixing @sidlatau! :grin: @Chaitanyabsprip please re-open if there are still issues
