### ISSUE TITLE
Jank caused due to result in floating window

### ISSUE THREAD

**Issue by Chaitanyabsprip** [rcarriga/vim-ultest#65]
Language: Dart/Flutter

I would prefer to have a way to increase the hold time before the plugin pops up the floating window with the test result. It causes jank when trying to move through the buffer. A "hoverDelay".

<img width="722" alt="image" src="https://user-images.githubusercontent.com/55058351/130137765-7e5b0ab6-d848-4982-b4c7-3af264d669cf.png">

**Comment by rcarriga** [comment]
The popup time is based on your `updatetime` setting. I'm guessing you have it set very low, which has a number of issues separate to vim-ultest.

If you don't want to change `updatetime` time you can do `let g:ultest_output_on_run = v:false` to disable the popup automatically showing, instead using `:UltestOutput` to show when you want to

**Comment by Chaitanyabsprip** [comment]
I appreciate your timely response, I will try out your suggestion and update this issue respectively. Thank you.
