### ISSUE TITLE
Configure mappings for the attach window

### ISSUE THREAD

**Issue by DanCardin** [rcarriga/vim-ultest#66]
So far, loving the plugin! I haven't managed to make any other test plugin stick yet (including `nvim-dap-ui`) for various reasons, but this one seems the most ergonomic that I've tried.

**Describe the bug**
Is it either possible today, or possible to add customizations to the mappings used by the floating window on `:UltestAttach`?
Currently `<c-c>` in that window closes the window. Personally in these sorts of windows, i ctrl-c all the time, so this makes working with the window rather more difficult.

**Expected behavior**
I'd love to be able to run ctrl-d, like on a terminal, and/or a way to exit insert mode after you've entered it and just directly `:q`

**Comment by rcarriga** [comment]
Thanks for the great feedback! :smile: 

The attach window is just a regular terminal window so you can use `tnoremap` or if you want filetype specific the filetype is `UltestAttach` which can be used with `FileType` autocommands. That should suffice for any custom mappings
