### ISSUE TITLE
Binding anything to C-W will break the summary

### ISSUE THREAD

**Issue by dahmc** [rcarriga/vim-ultest#79]
**Describe the bug**
When anything is bound to Control-w, the summary wont open without first showing an error

**To Reproduce**

add this to your vimrc. It can be any command, really.
```
nnoremap <C-W> :noh<CR>
```

**Expected behavior**
Summary opens without errors

**Screenshots**

![Screenshot 2021-11-22 at 15 57 01](https://user-images.githubusercontent.com/75008413/142883619-990b9153-a78a-4010-b4dd-7537c6f9c9a3.png)

It seems that <C-W> is used internally by the plugin?

**Comment by rcarriga** [comment]
Should be fixed in latest commit, please let me know!

**Comment by dahmc** [comment]
Works like a charm, thanks a lot for the quick fix!
