### ISSUE TITLE
How do you focus the output window?

### ISSUE THREAD

**Issue by Rofer11607** [rcarriga/vim-ultest#83]
**Describe the bug**
I can't find the keybinding to focus the output, scroll, visual mode ect..
I've looked through the docs, help file and the plugin to see if I can find, can someone point me in the right direction?

Logs should be created using `ULTEST_LOG_LEVEL=DEBUG ULTEST_LOG_FILE=vim-ultest.log nvim <test-file>` and added here as well

**To Reproduce**
run ul test

**Expected behavior**
I'm looking for a keybinding to focus on this window 
<img width="713" alt="image" src="https://user-images.githubusercontent.com/55964540/143975188-bf83ea2a-cbce-4688-beff-d1c8f7c46dd1.png">

**Screenshots**

**Additional context**

**Comment by rcarriga** [comment]
You can use the `<Plug>(ultest-output-jump)` mapping to jump to the window
