### ISSUE TITLE
UltestClear does not do anything

### ISSUE THREAD

**Issue by mflova** [rcarriga/vim-ultest#88]
**Describe the bug**
UltestClear command doest not seem to do anything. Checked after the use of different commands and the result is always the same.
The tests and all the other commands are working fine. The tests are launched from vim-test with Python3 (Instead of Python2) with the provided command `python3 -m pytest file.py`. In my case, it is not working with pytest, but I did not try with others.

To be honest I do not know how to create or access the log file despite the instructions. If somebody tell me how to do it, I will do it. Sorry for the inconvenience!

**To Reproduce**
Minimal code example:
```python
 def test_numeric():
    assert 1
```
Then executing `:Ultest` and `:UltestClear`

**Expected behavior**
Marks that indicate whether the test was succesful or not should be cleared.

**Screenshots**
![image](https://user-images.githubusercontent.com/67102627/147417529-f623ac5b-bb81-430b-a0a4-be40226d4581.png)

**Additional context**
-

**Comment by rcarriga** [comment]
Thanks for the report! Should be working with the latest commit :grin:

**Comment by mflova** [comment]
Yes! It is working now. Thanks :)
