### ISSUE TITLE
The summary is garbled when the test case contains Japanese characters

### ISSUE THREAD

**Issue by yamakeeeeeeeeen** [rcarriga/vim-ultest#90]
**Describe the bug**

If the test case contains Japanese characters, the test case displayed in the summary will be garbled.

language: typescript, ruby
test-library: jest, rspec

**To Reproduce**
Open the following test case summaries.

```ts
// example.test.ts
describe('ああ', () => {
  test('いい', () => {
  });
});
```

**Expected behavior**
I want to make sure that the summary is not garbled.

**Screenshots**

![image](https://user-images.githubusercontent.com/53547520/147915121-5f0d3398-89f6-41c6-8483-237352363ceb.png)

**Additional context**
The settings related to Japanese are as follows.

```
set encoding=utf-8
scriptencoding utf-8
set fileencodings=utf-8,sjis,cp932,euc-jp
```

**Comment by rcarriga** [comment]
Thanks for the report! Should be working fine now

**Comment by yamakeeeeeeeeen** [comment]
@rcarriga 
Thanks for the quick fix!
I've confirmed that it's fixed :)
