### ISSUE TITLE
Ultest is not expand for Rspec (ruby)

### ISSUE THREAD

**Issue by the-moriarty** [rcarriga/vim-ultest#91]
**Describe the bug**
Instead of showing all the specs, the summary only show one line.  To expand the tests i need to keep pressing $ (first time) and w (other times)

**To Reproduce**
Run Ultest
Open SUmmary

**Expected behavior**
Show all the test gracefully

**Screenshots**
When i open the summary:

![image](https://user-images.githubusercontent.com/97059083/148674142-675db98b-90d6-4c18-8105-7f95b4b46cf9.png)

After pressing one $ and two w:

![image](https://user-images.githubusercontent.com/97059083/148674146-b170b702-1dfc-429a-a032-2a09a52249c1.png)

**Additional context**
I want to have all tests already expand without needing to press w a lot of times.

**Comment by rcarriga** [comment]
Please try with the latest commit :smile:

**Comment by the-moriarty** [comment]
Fixed!
