### ISSUE TITLE
Error: vim-ultest encountered an unknown error on startup

### ISSUE THREAD

**Issue by diegoulloao** [rcarriga/vim-ultest#96]
**Describe the bug**
When I open my js test file (jest) I get this message at the status bar:

```
Error: vim-ultest encountered an unknown error on startup, check v:exception
```

I tried to run `Ultest` command anyways but nothing happens.

```
NVIM v0.6.1
Build type: Release
macOs Monterrey 12.1
```

No logs created.

**To Reproduce**
I'm just opening the file and running the command.

**Expected behavior**
Not to see an error message at the status bar and see the tests running when I put `Ultest` command.

**Screenshots**
<img width="1440" alt="Captura de Pantalla 2" src="https://user-images.githubusercontent.com/45423661/150415177-6e334f82-3dbd-4f64-b730-5336c11a7d81.png">

**Additional context**
`TestFile` works good.

**Comment by rcarriga** [comment]
Can you please pull the latest commit and then paste the error message shown?

**Comment by diegoulloao** [comment]
> Can you please pull the latest commit and then paste the error message shown?

This is latest commit and some checks are not passing:
https://github.com/rcarriga/vim-ultest/commit/b1ac774890790231252d0ffff967827478fbbd56

**Comment by rcarriga** [comment]
That's not the latest commit, and please ignore failing pipeline it is just a configuration issue for the tests. Latest commit https://github.com/rcarriga/vim-ultest/commit/e5b137d5ff98f3d570d6ec5b440c3223402f2447

**Comment by diegoulloao** [comment]
> That's not the latest commit, and please ignore failing pipeline it is just a configuration issue for the tests. Latest commit [e5b137d](https://github.com/rcarriga/vim-ultest/commit/e5b137d5ff98f3d570d6ec5b440c3223402f2447)

I pulled the latest commit:
```
commit 6cec1a394fbe4c3dc813c647b08bf323c085e370
Author: Rónán Carrigan <rcarriga@tcd.ie>
Date:   Thu Jan 20 21:28:10 2022 +0000

    tests: auto mode for asyncio
```

And I get the following message:
```
Error: vim-ultest encountered an unknown error on startup Vi(return):E117: Función desconocida:
_ultest_get_nearest_test
```

**Comment by diegoulloao** [comment]
FYI:
Función desconocida = Unknown function in spanish

**Comment by rcarriga** [comment]
What is the output of `:checkhealth provider`?

**Comment by diegoulloao** [comment]
> What is the output of `:checkhealth provider`?

```

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /opt/homebrew/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.9.9
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [arm64-darwin21]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v17.0.1
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed
```

**Comment by rcarriga** [comment]
Oh have you run `:UpdateRemotePlugins`?

**Comment by diegoulloao** [comment]
> Oh have you run `:UpdateRemotePlugins`?

I didn't run that command.

**Comment by rcarriga** [comment]
You need to run that after installing, normally there is a more helpful message but it matched the English message which is why you didn't see it. It will now instead match the error code

**Comment by diegoulloao** [comment]
> You need to run that after installing, normally there is a more helpful message but it matched the English message which is why you didn't see it. It will now instead match the error code

Now it's working! Thank you very much!

This is additional, but I can't see the dot icon because I'm using Hack Nerd Fonts (I must use it).
It's possible specify the icon? So I could paste a Hack Nerd Font icon that works.

**Comment by rcarriga** [comment]
See ':h g:ultest_pass_sign`, the docs list all of the signs you can change

**Comment by diegoulloao** [comment]
> See ':h g:ultest_pass_sign`, the docs list all of the signs you can change

where the docs is? can't find it

**Comment by diegoulloao** [comment]
> See ':h g:ultest_pass_sign`, the docs list all of the signs you can change

I found the docs:
https://github.com/rcarriga/vim-ultest/blob/master/doc/ultest.txt

Thank you!
