### ISSUE TITLE
Variable for Where to Split Buffer

### ISSUE THREAD

**Issue by trisys3** [rcarriga/vim-ultest#97]
This would essentially replace `g:ultest_summary_open`. Instead of a long, complicated, but versatile command, this would be a variable for opening to the left, right, top or bottom. The name could be bikeshed later, but for purposes of this issue I'll use `g:ultest_summary_position`.

Basically:
* `let g:ultest_summary_position = right` would do the same thing as the default:
    *  `let g:ultest_summary_open = "botright vsplit | vertical resize " . g:ultest_summary_width`
* `let g:ultest_summary_position = left` would do:
    * `let g:ultest_summary_open = "topleft vsplit | vertical resize " . g:ultest_summary_width`
* `let g:ultest_summary_position = top`:
    * `let g:ultest_summary_open = "topleft split | resize " . g:ultest_summary_width`
* `let g:ultest_summary_position = bottom`:
    * `let g:ultest_summary_open = "botright split | resize " . g:ultest_summary_width`

Not sure how this would deal with legacy code. I suppose `g:ultest_summary_position` could be empty by default, or `g:ultest_summary_width` could.

**Comment by rcarriga** [comment]
I don't think I see the need for this. As you've just shown, there is a very simple alternative for each option already, they are not long and complicated. On the other hand, we'd need to handle two conflicting options, as you said, and the new option would be much more limited than the existing one.

**Comment by trisys3** [comment]
Hmmm... Do you think a documentation update would be useful? I'm relatively familiar with vimL and was able to hack those up, but someone who's never created a vim plugin before would likely have no idea.

**Comment by rcarriga** [comment]
Yes I could definitely see docs being the solution here, happy to add them
