### ISSUE TITLE
No matching autocommands: UserUltestPositionsUpdate

### ISSUE THREAD

**Issue by trisys3** [rcarriga/vim-ultest#98]
**Describe the bug**
Like the title states, I'm getting `No matching autocommands: UsetUltestPositionsUpdate` in the status line.

**To Reproduce**

Run `UltestStop` or `UltestStopNearest`. The message appears whether or not any tests are currently running.

**Expected behavior**
No message claiming there aren't any auto-commands. I don't particularly care, and there are ways to check this for debugging purposes if I did care.

**Screenshots**

**Additional context**
This happens even if I remove all my `vim-test` & `vim-ultest` configuration from my `vimrc`. If you need my entire `vimrc` or you think any part of it could be causing this, or if you need any other info, please ask and I'll provide it if I can.

I'm using `vim`. The version is 8.2, with patches 1-3450. Not sure if this is the latest, but it's pretty darn recent.

**Comment by rcarriga** [comment]
Looks like Vim now requires autocmds to exist before calling them, I've added a workaround as suggested by the docs

**Comment by trisys3** [comment]
Thanks, that works!

And thanks for the great plugin, it makes testing much more convenient!
